### ISSUE TITLE
About the masknewgenerate

### ISSUE THREAD

**Issue by mumuner** [Vill-Lab/SIAMH#1]
Hi, I read your code (https://github.com/Vill-Lab/SIAMH/tree/main/fastreid/engine/train_loop.py), I confused about the masknewgenerate function. Why you use softmax plus sigmoid function to generate the mask? Can you give me the reason? Please.

**Comment by yuanpengtu** [comment]
Thanks for your attention. Actually, the masknewgenerate function is used to convert feature map of the teacher model into masked form. Specifically, the value of the generated mask should be between 0 and 1 to filter out the salient regions. Therefore, the softmax and sigmoid function is used to reach this goal.
